/* Modelagem Básica*/

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL  - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSO DE MODELAGEM */

/* FASE 01 E FASE 02 - AD DE DADOS */

MODELAGEM CONCENTUAL - RASCUNHO UM EXEMPLO A CIMA NO MODELAGEM BÁSICA
MODELAGEM LÓGICA - PEGA O RASCUNHO E TRÁS PARA UM PROGRAMA DE MODELAGEM.


/* FASE 03 - DBA / AD */

MODELAGEM FÍSICA -  SCRIPTS DE BANCO
